### ISSUE TITLE
ocsp.sectigo.com

### ISSUE THREAD

**Issue by p1r473** [kang49/kang49regexblacklistproject#1]
hi @kang49 
ocsp.sectigo.com is for OCSP Stapling
OCSP (Online Certificate Status Protocol) is one of two common schemes used to maintain the security of a server and other network resources.
https://support.sectigo.com/PS_KnowledgeDetailPage?Id=kA01N000000zFJn

**Comment by kang49** [comment]
Okay Thanks, You can "pihole -g" for update your Pihole adlist.
